---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: rayapallisuresh/api
        env:
        - name: REVERSE_SERVICE
          value: "http://reverse-service"
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 32345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deployment
  labels:
    app: reverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse
  template:
    metadata:
      labels:
        app: reverse
    spec:
      containers:
      - name: reverse
        image: rayapallisuresh/reverse
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-service
spec:
  selector:
    app: reverse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

